bin_addr = ":80"
log_level = "debug"
database_url = "host=localhost dbname=restapi_dev user=postgres password=Kv3 sslmode=disable"
session_key = "sfsqd1"
test = "postgres://postgres:Koras1993@localhost/restapi_dev?sslmode=disable"
